
version: 0.2

phases:
  pre_build:
    commands:
    - echo Installing pip
    - export PATH=$PATH:/root/.local/bin
    - wget https://bootstrap.pypa.io/get-pip.py
    - python --version
    - python get-pip.py --user
    - python -m pip install mkdocs mkdocs-material pymdown-extensions fontawesome_markdown --user
  build:
    commands:
    - echo Building MkDocs Site
    - python -m mkdocs build
    - aws s3 sync site/ s3://demos.bastil.cloud/byod/ --delete
