site_name: Bring your own data labs
site_url: https://github.com/BastLeblanc/aws-byod-immersion-day
repo_url: https://github.com/BastLeblanc/aws-byod-immersion-day
repo_name: 'BastLeblanc/aws-byod-immersion-day'
site_description: Bring Your Own Data Labs
docs_dir: labs
nav:
  - Intro: README.md
  - 0-Prerequisites: 00_Prerequisites/README.md
  - 1-Ingestion: 01_ingestion_with_glue/README.md
  - 2-Orchestration: 02_orchestration/README.md
  - 3-Interactive-SQL: 
    - 3-Interactive-SQL lab: 03_interactive_sql_queries/README.md
    - 3-1 SQL Optional lab 1 : 03_interactive_sql_queries/optional.md
    - 3-2 SQL Optional Amazon Athena Best Practices: 03_interactive_sql_queries/athena_best_practices.md
  - 4-Visualisation:  04_visualization_and_reporting/README.md
  - 5-Transformations: 05_transformations/README.md
theme:
  highlightjs: true
  #name: 'bootstrap'
  name: 'material'
  language: 'en'
  palette:
    primary: 'blue grey'
    accent: 'orange'
plugins:
  - search
#  - pdf-export:
#      verbose: false
extra_css:
#  - css/extra.css
use_directory_urls: false
extra:
  social:
#    - type: 'github'
#      link: 'https://github.com/...'
#    - type: 'twitter'
#      link: 'https://twitter.com/...'
markdown_extensions:
  - admonition
  - smarty
#  - markdown.extensions.codehilite:
#      guess_lang: false
#  - markdown.extensions.def_list
#  - markdown.extensions.footnotes
#  - markdown.extensions.meta
  - toc:
      permalink: true
#  - pymdownx.arithmatex
#  - pymdownx.betterem:
#      smart_enable: all
#  - pymdownx.caret
#  - pymdownx.critic
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
#  - pymdownx.inlinehilite
#  - pymdownx.magiclink
#  - pymdownx.mark
#  - pymdownx.smartsymbols
#  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
#  - pymdownx.tilde
  - fontawesome_markdown

